### ISSUE TITLE
Set up CI and Code Climate

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1]
@kntsoriano Could you set this up for me please?

I'm happy to use either GHA or Circle for CI. I believe GHA will be faster but you might want to just go with Circle for now as we have existing config. Your choice :)

This is the Code Climate ID: 7646f68efcfb351226b48cf3e8af112e2c46463de13c80ce513d71cd890f5df6

---

- [ ] Set up CI
- [ ] Set up Code Climate
- [ ] Get me a CI badge for the README :)

**Comment by ErikSchierboom** [comment]
@kntsoriano If you need any help with GitHub Actions, I have some experience there.

**Comment by kntsoriano** [comment]
@iHiD I'll try GHA. Can you add me as a repository collaborator so I could create a workflow? Thanks.

@ErikSchierboom I will ask you if I get stuck. Thank you so much!

**Comment by iHiD** [comment]
@kntsoriano Do you have the right permissions now?

**Comment by kntsoriano** [comment]
Yes. Thanks.

**Comment by iHiD** [comment]
I've now done this with [this commit](https://github.com/exercism/v3-website/commit/53b2176984f8229db07b7a71bcaa2f18862f92ac)
