### ISSUE TITLE
Task: Upgrade v3 to Highlight.js v11

### ISSUE THREAD

**Issue by joshgoebel** [exercism/website#1047]
Version 11 was just released and now includes Wren support among the many other fixes.

https://github.com/highlightjs/highlight.js/releases/tag/11.0.0

**Comment by kntsoriano** [comment]
We've already upgraded to Highlight JS according to our package.json. Is the update still not applied?

**Comment by iHiD** [comment]
@kntsoriano I think maybe this issue just didn't get closed?
