### ISSUE TITLE
Choose name for the things that are sort of serializers but sort of aren't.

### ISSUE THREAD

**Issue by iHiD** [exercism/website#115]
@kntsoriano @ErikSchierboom @SleeplessByte You all raised concerns(?) about my use of the word serializers, and also the way they're structured.

I think I'm ok with having these objects as commands for now, as they're very easy to change **from** commands to something else later if needed, and as they have only one public interface method I think they make sense. I agree with @kntsoriano's feeling that an object with a `to_hash` method also makes sense, but as I've done the work to make them commands, let's stick with that for now.

But I would like to feel like we're getting the naming right.

To clarify, the purpose here is to create some sort of arrangement of data that is appropriate to power the React Components and/or respond to CLI requests.

As examples, we currently have two:
1. In production for the CLI, which returns the info needed for the CLI to utilise a solution
2. In v3 for the React component to list the correct tracks, with their data and user-specific data.

The first is serializing/formating/representing a solution into some custom JSON object. The second is doing the same with an array of tracks.

What are these doing? Are they serialzing to a custom object? (which was my initial feeling). Are they formatting the object/data? Are they representations of some data?

If we can establish that first, then naming them might become easier 🙂

**Comment by SleeplessByte** [comment]
Are they meant to be the final step before rendering? Or are they meant to render/determine what is rendered? Because currently they seem to be a _bit of both_, which is where my concern lies.

> To clarify, the purpose here is to create some sort of arrangement of data that is appropriate to power the React Components and/or respond to CLI requests.

This description is also incredibly broad and sorta applies to everything connected to serving a request. 

----

It seems to me that you're trying to (re-)represent a resource (a resource can be a single "solution", or a list of tracks, etc.). And that means that you're basically trying to output hypermedia (resource in the context of hypertext, including hyperlinks). If that is the case, `Serializer` isn't that bad of a name -- but if you can add validation to the object, it would become a `Contract`, which seems to be the appropriate noun for what's going on.

**Comment by iHiD** [comment]
So in my mental model they are serialisers. They are taking an object, or an array, and shaping that data into a format to render. For example, they are taking an array of tracks and formatting it into the right JSON shape. The only logic in them is whether certain keys can be added or not (ie whether the user has joined that track). But even in that situation, they are just determining whether some keys are null/missing or whether they have some value. 

So while they do have logic to determine what the values of certain keys are, the logic they have is purely rendering logic (which is why the searching step is separate, for example).

**Comment by SleeplessByte** [comment]
I think some of the issue comes from relying on the built-in JSON "Renderer" (which is what it's called) to do _part_ of the serialisation/renderer. 

If the final step were `to_json` instead of `to_hash`, and you'd use `render plain: ..., content_type: 'application/json'`, all that relying on magic would be solved.

**Comment by ErikSchierboom** [comment]
> For example, they are taking an array of tracks and formatting it into the right JSON shape

Aren't they formatting it into the right API shape? As in: the current serializers don't actually have any JSON knowledge? 

> If the final step were to_json instead of to_hash

But isn't the renderer Rails' built-in `json` function? It looks me like the serializer is just about putting the data in the right format, not about actually outputting any JSON/HTML/XML/whatever format. So I actually like `to_hash` better I think.

>  And that means that you're basically trying to output hypermedia (resource in the context of hypertext, including hyperlinks). If that is the case, Serializer isn't that bad of a name -- but if you can add validation to the object, it would become a Contract, which seems to be the appropriate noun for what's going on.

The resource bit resonates with me, as an API is basically a way to access a certain resource. In other API descriptions, the format that is being returned (i.e. the _interface_ of the data that is returned) is sometimes referred to as the response.

**Comment by SleeplessByte** [comment]
> But isn't the renderer Rails' built-in json function? It looks me like the serializer is just about putting the data in the right format, not about actually outputting any JSON/HTML/XML/whatever format. So I actually like to_hash better I think.

`to_hash` only works because it's currently always returning a hash (without the guarantee that it is), and because hashes can be JSON-serialized. That implicitly says something about the fact that not everything can be JSON-serialized, and thus it matters.

**Comment by iHiD** [comment]
From reading this, I think the actual problem that @SleeplessByte specifically raised isn't this bit at all, it's what happens after. 

ie, he doesn't necessarily care (for the context of this discussion) about how the data gets to that final line, or what format it is in, but he cares that we don't magically go from a hash to JSON and just presume that will work. I think it ties into the wider feeling that a JSON API without media queries etc is a "weak" contract.

(Correct me if I'm wrong DJ - but it's helped me to frame the conversation understanding that)

So I think there are two intertwined discussions:
1) What's the code to do the rendering. I defaulted to what I consider Rails "standard" or `render json: some_hash`, which DJ doesn't like, but also which we'd probably pragmatically agree is good enough for now, as long as there is some test that checks the rendering doesn't end up with unserializable things in it.
2) The thing that gets the data to the hash isn't serializing to an output type - it's building a response. So maybe these are "Response Builders" or "Response Formatters", which should then be serialized into something somehow (which is (1) which we're kicking into the post-beta-launch grass).

So something like `BuildAPIResponseForTracks` is a more sensible name for now (or `ResponseBuilder::Tracks.new(...)to_hash` if it wasn't a command)?

**Comment by kntsoriano** [comment]
I think that the track list is a `StudentTrackList` read model. We can create a separate `read_models/` folder to further separate them for clarity and to make the distinction that these aren't DB backed. The problem is that it maybe a "loaded" term as we're not using CQRS.

**Comment by ErikSchierboom** [comment]
> to_hash only works because it's currently always returning a hash (without the guarantee that it is)

Yeah, that assumption seemed to me to make sense, that `to_hash` would also actually return a hash. But apparently that is not as simple :)

> So something like BuildAPIResponseForTracks is a more sensible name for now (or ResponseBuilder::Tracks.new(...)to_hash if it wasn't a command)?

What about just `TracksResponse`?

**Comment by iHiD** [comment]
> I think that the track list is a StudentTrackList read model.

The problem is that there could be 3 different StudentTrackList models in time. One for React, one for a public API, etc. And because we have to continue to support old CLI versions, we will need to have old serializations of the data. So I don't feel they are "models", they are representations of the data in some format. 

Over time, we'll have lots of legacy versions of these. So whatever we do, at some stage we'll have to version these.

**Comment by kntsoriano** [comment]
@iHiD Ah yes. Good point :)
