### ISSUE TITLE
TypeError in /docs/organisation

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1208]
## Error in v3 (client side)

**TypeError** in **/docs/organisation**
Cannot redefine property: __THREE_DEVTOOLS__

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/60bed2e367c4d800078f2d5f?event_id=60e1c037007f946d1cb20000&i=gh&m=ci)

## Stacktrace

    global code:37 - null

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/60bed2e367c4d800078f2d5f?event_id=60e1c037007f946d1cb20000&i=gh&m=ci)

*Created by Jeremy Walker via Bugsnag*

**Comment by kntsoriano** [comment]
@iHiD I will close this because it is related to someone having a browser extension outside of what we're using. I think this will possibly go away soon too if we use Hotwire.

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/settings/communication_preferences**](https://app.bugsnag.com/exercism/v3-client-side/errors/60bed2e367c4d800078f2d5f?event_id=61060ea2007f8fce3f3a0000&i=gh&m=ra)

**Comment by iHiD** [comment]
This is an error from a 3rd party browser plugin

Comment added in Bugsnag by Karlo Soriano
[**TypeError** in **/tracks/python/exercises/making-the-grade/edit**](https://app.bugsnag.com/exercism/v3-client-side/errors/60bed2e367c4d800078f2d5f?event_id=61261e05007f932cd7700000&i=gh&m=cm)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/docs/organisation**](https://app.bugsnag.com/exercism/v3-client-side/errors/60bed2e367c4d800078f2d5f?event_id=612f701a007f8ed569060000&i=gh&m=ra)

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/docs/organisation**](https://app.bugsnag.com/exercism/v3-client-side/errors/60bed2e367c4d800078f2d5f?event_id=61378ec3007f9db561d40000&i=gh&m=fx)
