### ISSUE TITLE
TypeError in /tracks/common-lisp

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1223]
## Error in v3 (client side)

**TypeError** in **/tracks/common-lisp**
Cannot read property 'map' of undefined

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/60e5a68af9f24500081a0978?event_id=60e5a68a007f8a60ce700000&i=gh&m=ci)

## Stacktrace

    app/javascript/components/common/site-updates-list/SiteUpdate.tsx:34 - SiteUpdate

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/60e5a68af9f24500081a0978?event_id=60e5a68a007f8a60ce700000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/dashboard**](https://app.bugsnag.com/exercism/v3-client-side/errors/60e5a68af9f24500081a0978?event_id=60f52fee007fa58597320000&i=gh&m=ra)

**Comment by kntsoriano** [comment]
@iHiD It's the same error as https://github.com/exercism/website/issues/1205. It seems that some site updates do not have their cacheable rendering data updated. Do we a cron job for this already?
