### ISSUE TITLE
Which font-smoothing to use?

### ISSUE THREAD

**Issue by iHiD** [exercism/website#124]
In chrome/firefox, you can set `font-smoothing` to antialiasing or subpixel antialiasing. Subpixel is more modern and the default. "Standard" antialiasing is the older way, but is often used to make fonts look more like in designs.

There is **much** debate about this online (e.g. [apple.com "downgrades" to standard](https://www.apple.com/) as do [Google Fonts](https://github.com/google/fonts/issues/1170) website, whereas many [hate it](https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/).)

---

Here's a specific example to discuss:

This is the Figma design. Figma has it as 700 weight:

<img width="332" alt="Screenshot 2020-09-29 at 22 23 27" src="https://user-images.githubusercontent.com/286476/94618049-75d84f80-02a2-11eb-9d58-33e5c4fc8c3a.png">

This is 700 weight with (default) subpixel antialiasing:
<img width="604" alt="Screenshot 2020-09-29 at 22 17 02" src="https://user-images.githubusercontent.com/286476/94617569-b08db800-02a1-11eb-8fa1-46e6bd9964c8.png">

This is the weight reduced down to 600, still with with subpixel antialiasing:
<img width="616" alt="Screenshot 2020-09-29 at 22 17 20" src="https://user-images.githubusercontent.com/286476/94617572-b1264e80-02a1-11eb-933f-1de08256f031.png">

This is 700 weight with the change to "standard" antialiasing:
<img width="607" alt="Screenshot 2020-09-29 at 22 17 50" src="https://user-images.githubusercontent.com/286476/94617573-b1264e80-02a1-11eb-8a43-8f43e0d9a267.png">

The last looks closet to the design. 600 looks closer if we're using subpixel. 

I am generally **strong against** reducing the font-weight down to look more like figma, as for linux/windows it gets really thin fast. So I'm **pro** using old-school antialiasing. And the fact that apple.com does it makes me ok with it.

One other option is to use antialiasing for headings and subpixel antialiasing for blocks of texts.

But I also welcome other opinions if anyone has any 🙂 

---

If you read this and have no opinion (or none you care to share), please give this a 🚀 emoji, and I shall take it as a "do whatever you like" prompts 😉

**Comment by SleeplessByte** [comment]
Use it on presentational items, or large text, if you want.

Leave it up to the browser for all regular sized text.

**Comment by iHiD** [comment]
Yippy! :)
