### ISSUE TITLE
Mentor discussion showing 0 comments but shows several in "Open discussion"

### ISSUE THREAD

**Issue by Steffan153** [exercism/website#1360]
In the mentor_discussions page (in my case https://exercism.lol/tracks/ruby/exercises/scrabble-score/mentor_discussions) it only shows 0 comments (though it says it's my turn to respond):
![image](https://user-images.githubusercontent.com/40404519/128408847-686fb233-dab5-4924-af49-4ab9a4467156.png)

But in the "Open discussion", it shows all my iterations and mentor's comments: 
![image](https://user-images.githubusercontent.com/40404519/128408949-a9b41a38-c1e0-47b5-8838-17f32988fe91.png)
(it goes on a more than that)

Username is Steffan153 in case it's user-specific.

Thanks!

**Comment by iHiD** [comment]
Thanks. Is that better now? If so, it's an ETL issue, which I've noted [here](https://github.com/exercism/website/pull/579#issuecomment-893787231) now.

**Comment by Steffan153** [comment]
Yep, it's fine now.

**Comment by iHiD** [comment]
Thanks :)
