### ISSUE TITLE
TypeError in /tracks/python/exercises/currency-exchange/solutions/BethanyG

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1370]
## Error in v3 (client side)

**TypeError** in **/tracks/python/exercises/currency-exchange/solutions/BethanyG**
Cannot read property 'links' of undefined

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/610d967a0955e90007df664f?event_id=610d967a007f9a7758560000&i=gh&m=ci)

## Stacktrace

    app/javascript/components/common/SolutionView.tsx:38 - SolutionView

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/610d967a0955e90007df664f?event_id=610d967a007f9a7758560000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by kntsoriano** [comment]
Closing in favor of https://github.com/exercism/website/issues/1415.
