### ISSUE TITLE
TypeError in /tracks/ruby/exercises/lasagna/solutions/iHiD

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1415]
## Error in v3 (client side)

**TypeError** in **/tracks/ruby/exercises/lasagna/solutions/iHiD**
Cannot read property 'links' of undefined

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/611fdef8be7cf1000876c7aa?event_id=611fdef8007f87d80f5a0000&i=gh&m=ci)

## Stacktrace

    app/javascript/components/common/SolutionView.tsx:38 - SolutionView

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/611fdef8be7cf1000876c7aa?event_id=611fdef8007f87d80f5a0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by kntsoriano** [comment]
@iHiD This crashes because this solution does not have iterations: https://exercism.lol/tracks/ruby/exercises/lasagna/solutions/iHiD. Is this an ETL issue?

**Comment by iHiD** [comment]
It's probably me fucking around in the DB :)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Error** in **/tracks/python/exercises/robot-name/solutions/7676694207676**](https://app.bugsnag.com/exercism/v3-client-side/errors/611fdef8be7cf1000876c7aa?event_id=612fec47007f9b9847300000&i=gh&m=ra)

**Comment by kntsoriano** [comment]
@iHiD We have encountered this again with this: https://exercism.org/tracks/python/exercises/ghost-gobble-arcade-game/solutions/ccac.

The solution is published but there are no published iterations. Is this a data issue?

**Comment by iHiD** [comment]
It happens when all iterations are deleted. This should then unpublish the solution, but doesn't. There's a separate bug open for that. I'll ask @ErikSchierboom to prioritise it.

**Comment by iHiD** [comment]
https://github.com/exercism/exercism/issues/5909#issuecomment-936076451

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/tracks/csharp/exercises/log-levels/solutions/Eskevv**](https://app.bugsnag.com/exercism/v3-client-side/errors/611fdef8be7cf1000876c7aa?event_id=614d451d008121f723f40000&i=gh&m=fx)
