### ISSUE TITLE
System tests struggle to follow React URLs

### ISSUE THREAD

**Issue by iHiD** [exercism/website#143]
An interesting one that I don't have a neat fix for. 

[This test](https://github.com/exercism/v3-website/blob/master/test/system/flows/join_track_test.rb#L13) fails when the React component is used (it passes on master because we're rendering in Rails).

The reason it fails is:
- The react component is setting the `href` of the `a` to be `web_url` ([serialized here](https://github.com/exercism/v3-website/blob/master/app/serializers/serialize_tracks.rb#L26).
- That `web_url` uses the `host` of the test environment, which is `https://test.exercism.io`. So when capybara clicks the link, it redirects to that non-existant URL and breaks.

There are two simple changes that would fix this:
1) Use a path, not a URL
2) Change the host to be `localhost` (or whatever capybara can follow).

I don't want to do (2) because I like that it's a specific test host. I feel it's important that `test` and `development` have different hosts, else we could easily hard-code `localhost` into the code base and see it work in dev, and tests passing, but it fail in production. By having `tests.exercism.io` as our host, we have an extra line of defense for this.

So then we could do (1). In the serializer, we could use `_path` in test env, and `_url` in dev/production. Again, I'm not a massive fan as it means that we are not testing the production code in tests, which could mean we leaked `_path` into the codebase and wouldn't know until production broke. 

Another option would be to have the React component stripe the host in test mode, but this comes with similar issues to above.

Yet another option would be to have `web_path` and `web_url`. The React components could use `web_path` and consumers could use `web_url`. This might be the most straight-forward option.

Does anyone have any better ideas or any here that they like?

**Comment by SleeplessByte** [comment]
>  So when capybara clicks the link, it redirects to that non-existant URL and breaks.

This is really the thing to solve. If you _want_ `tests.exercism.io` to work, nginx it. Or similar.

I don't like any of the other options. I think your reasoning to not like them is sound.

**Comment by iHiD** [comment]
> This is really the thing to solve. If you want tests.exercism.io to work, nginx it. Or similar.

That's a good idea. If we set it to local.exercism.io, then we could DNS that to localhost? (like lvh.me)

**Comment by SleeplessByte** [comment]
Absolutely! Any of those solutions would work.

**Comment by ErikSchierboom** [comment]
Good idea @SleeplessByte!

**Comment by kntsoriano** [comment]
This is solved by https://github.com/exercism/v3-website/blob/master/test/support/capybara_helpers.rb.
