### ISSUE TITLE
TypeError in /tracks/nim/exercises/hello-world/edit

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1511]
## Error in v3 (client side)

**TypeError** in **/tracks/nim/exercises/hello-world/edit**
can't access property "languageData", t is undefined

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6128edcf49dd720007c2e135?event_id=6128edcf007f816bd8660000&i=gh&m=ci)

## Stacktrace

    app/javascript/components/misc/CodeMirror/languageCompartment.ts:113 - e/<

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6128edcf49dd720007c2e135?event_id=6128edcf007f816bd8660000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by ynfle** [comment]
Related to/the cause of https://github.com/exercism/exercism/issues/5703

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/tracks/nim/exercises/hello-world/edit**](https://app.bugsnag.com/exercism/v3-client-side/errors/6128edcf49dd720007c2e135?event_id=6128edcf007f8417a2000000&i=gh&m=fx)
