### ISSUE TITLE
Where should `#user_track_for` live?

### ISSUE THREAD

**Issue by iHiD** [exercism/website#155]
@kntsoriano said: Any opinion in finding the right place for `#user_track_for`? I think if we continue doing methods like this, we'll end up with a very large `User` class. Maybe we could talk about this in a separate issue.

_Originally posted by @kntsoriano in https://github.com/exercism/v3-website/pull/152#discussion_r499298653_

**Comment by iHiD** [comment]
I don't have a preference, really. Another option would be to have a `UserTrack.for(user, track)` method. I'd be happy with that as an alternative.

**Comment by kntsoriano** [comment]
I like that too!

**Comment by ErikSchierboom** [comment]
Me too!

**Comment by iHiD** [comment]
Cool. I'll update throughout 🙂
