### ISSUE TITLE
TypeError in /tracks/nim/exercises/hello-world/edit

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1551]
## Error in v3 (client side)

**TypeError** in **/tracks/nim/exercises/hello-world/edit**
can't access property "languageData", t is undefined

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/612b8b77e89ea50007d111c8?event_id=612b8b77007f9c7e41730000&i=gh&m=ci)

## Stacktrace

    app/javascript/components/misc/CodeMirror/languageCompartment.ts:113 - e/<

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/612b8b77e89ea50007d111c8?event_id=612b8b77007f9c7e41730000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by ynfle** [comment]
Related to/the cause of https://github.com/exercism/exercism/issues/5703
