### ISSUE TITLE
DB not seeding on start

### ISSUE THREAD

**Issue by neenjaw** [exercism/website#180]
When starting the system via `./bin/start --pull` it seems the DB is not seeding properly, so I get an initial error:

![Screenshot from 2020-10-08 16-27-30](https://user-images.githubusercontent.com/8953691/95519838-2faa7c80-0983-11eb-8ccf-80a18f0066db.png)

When I exec into the website container and run:

`bundle exec rake db:reset db:migrate db:seed`

It goes through the motions, dropping, creating, seeding and then I am able to see the website:

![Screenshot from 2020-10-08 16-29-27](https://user-images.githubusercontent.com/8953691/95519948-74ceae80-0983-11eb-9c97-f3dc6a03ca16.png)

(@iHiD can attest to this, he has waited for me several times while I have had to do this)

Is this seeding command being missed in the setup somewhere?

**Comment by iHiD** [comment]
_(Moved this to `v3-website` as the issue lies here)_

**Comment by neenjaw** [comment]
```bash
num_users = $(rails r "p User.count")
if [[ "${num_users}" -eq 0 ]]
then
    bundle exec bin/rails db:seed
fi
```

**Comment by neenjaw** [comment]
I can PR it if you like

**Comment by iHiD** [comment]
Nice. Does `-eq 0` need to be `-eq "0"` is is this fine?

Want to PR it and get another Hacktoberfest entry? :wink:

**Comment by neenjaw** [comment]
0 is equal to "0" in this sense because bash will cast the type to work

```
➜ num_users="0"; if [[ "${num_users}" -eq 0 ]]; then; echo "Hi"; fi;
Hi
➜ num_users=0; if [[ "${num_users}" -eq 0 ]]; then; echo "Hi"; fi; 
Hi
➜ num_users=1; if [[ "${num_users}" -eq "0" ]]; then; echo "Hi"; fi;

➜ num_users=1; if [[ "${num_users}" -eq 0 ]]; then; echo "Hi"; fi; 

```
