### ISSUE TITLE
ChunkLoadError in /tracks/python/exercises

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1987]
## Error in v3 (client side)

**ChunkLoadError** in **/tracks/python/exercises**
Loading chunk 5 failed.
(error: https://exercism-v3-assets.s3.eu-west-2.amazonaws.com/packs/js/5-22a8e3209896a94f8e69.chunk.js)

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6153008372b39e0007a918fb?event_id=61530083008257b747310000&i=gh&m=ci)

## Stacktrace

    app/javascript/packs/application.tsx:235 - 

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6153008372b39e0007a918fb?event_id=61530083008257b747310000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
See #1989

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ChunkLoadError** in **/users/confirmation**](https://app.bugsnag.com/exercism/v3-client-side/errors/6153008372b39e0007a918fb?event_id=6158d713008320ac66060000&i=gh&m=fx)

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ChunkLoadError** in **/users/confirmation**](https://app.bugsnag.com/exercism/v3-client-side/errors/6153008372b39e0007a918fb?event_id=6158d713008320ac66060000&i=gh&m=fx)
