### ISSUE TITLE
NotSupportedError in /docs/editions/teams

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1988]
## Error in v3 (client side)

**NotSupportedError** in **/docs/editions/teams**
CustomElementRegistry.define: 'turbo-frame' has already been defined as a custom element

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/615303ea32a3fc00077cb491?event_id=615303ea008271fecaf90000&i=gh&m=ci)

## Stacktrace

    app/javascript/packs/core.tsx:1 - 863

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/615303ea32a3fc00077cb491?event_id=615303ea008271fecaf90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
This is likely a Turbolinks error or double inclusion/execution of the turbo initialization code. May be valid.

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**NotSupportedError** in **/docs/organisation**](https://app.bugsnag.com/exercism/v3-client-side/errors/615303ea32a3fc00077cb491?event_id=6156c1320083186911290000&i=gh&m=fx)
