### ISSUE TITLE
ChunkLoadError in /tracks/php/exercises/hello-world/edit

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1989]
## Error in v3 (client side)

**ChunkLoadError** in **/tracks/php/exercises/hello-world/edit**
Loading chunk 18 failed.
(timeout: https://exercism-v3-assets.s3.eu-west-2.amazonaws.com/packs/js/18-21e477f40bf77c120045.chunk.js)

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/615315aead0ee700075108d1?event_id=615315ae008268f764a70000&i=gh&m=ci)

## Stacktrace

    app/javascript/packs/application.tsx:231 - 

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/615315aead0ee700075108d1?event_id=615315ae008268f764a70000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
Timed-out on loading a chunk. You can't solve this.

Related: #2022, #1918, #1784, #1716, #1679, etc.

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ChunkLoadError** in **/tracks/javascript/exercises/translation-service/edit**](https://app.bugsnag.com/exercism/v3-client-side/errors/615315aead0ee700075108d1?event_id=615956b10082ea54c8d70000&i=gh&m=fx)

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ChunkLoadError** in **/tracks/javascript/exercises/translation-service/edit**](https://app.bugsnag.com/exercism/v3-client-side/errors/615315aead0ee700075108d1?event_id=615956b10082ea54c8d70000&i=gh&m=fx)
