### ISSUE TITLE
InvalidStateError in /tracks

### ISSUE THREAD

**Issue by iHiD** [exercism/website#1994]
## Error in v3 (client side)

**InvalidStateError** in **/tracks**
Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6154bef6e07d430008bf4062?event_id=6154bef600824d360bd30000&i=gh&m=ci)

## Stacktrace

    https://exercism.org/tracks:182 - openAndSendRequest

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6154bef6e07d430008bf4062?event_id=6154bef600824d360bd30000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
This is likely because of the user's internet connection cutting out. It's similar to #2025

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**InvalidStateError** in **/tracks**](https://app.bugsnag.com/exercism/v3-client-side/errors/6154bef6e07d430008bf4062?event_id=6154bef600826796c6dd0000&i=gh&m=fx)
