### ISSUE TITLE
TypeError in /tracks/go/exercises/lasagna

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2000]
## Error in v3 (client side)

**TypeError** in **/tracks/go/exercises/lasagna**
r[0] is undefined

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6155db852cedc800079b94be?event_id=6155db850082e648ae6d0000&i=gh&m=ci)

## Stacktrace

    app/javascript/components/modals/student/useIterationSelector.tsx:23 - onSelected
    app/javascript/components/modals/student/IterationSelector.tsx:40 - onChange

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6155db852cedc800079b94be?event_id=6155db850082e648ae6d0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
This is likely a valid error.

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/tracks/go/exercises/lasagna**](https://app.bugsnag.com/exercism/v3-client-side/errors/6155db852cedc800079b94be?event_id=6155db850082e89fb2480000&i=gh&m=fx)
