### ISSUE TITLE
ReferenceError in /docs/tracks/delphi

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2003]
## Error in v3 (client side)

**ReferenceError** in **/docs/tracks/delphi**
MtPopUpList is not defined

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/61563db1bbd6f10007582e05?event_id=61563db10082f383d8ce0000&i=gh&m=ci)

## Stacktrace

    https://exercism.org/docs/tracks/delphi line 1 > injectedScript:1 - intervalId<

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/61563db1bbd6f10007582e05?event_id=61563db10082f383d8ce0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
This is an extension issue or Bing "translate" issue. We probably can't fix this.

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ReferenceError** in **/docs/tracks/delphi**](https://app.bugsnag.com/exercism/v3-client-side/errors/61563db1bbd6f10007582e05?event_id=61563db10082f2b902a60000&i=gh&m=fx)
