### ISSUE TITLE
TypeError in /tracks/python/exercises/currency-exchange/edit

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2006]
## Error in v3 (client side)

**TypeError** in **/tracks/python/exercises/currency-exchange/edit**
can't access dead object

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6156da68ecfa100007c1ae3b?event_id=6156da68008314bf7f300000&i=gh&m=ci)

## Stacktrace

    https://exercism.org/usage/js/script.js:1 - i

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6156da68ecfa100007c1ae3b?event_id=6156da68008314bf7f300000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
Likely an extension issue <https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/>

**Comment by iHiD** [comment]
Thanks!
