### ISSUE TITLE
TypeError in /tracks/go/concepts

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2014]
## Error in v3 (client side)

**TypeError** in **/tracks/go/concepts**
Cannot read properties of undefined (reading 'length')

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6157812345c2700008b7db83?event_id=6157812300837484e7dd0000&i=gh&m=ci)

## Stacktrace

    app/javascript/components/concept-map/ExerciseStatusBar.tsx:10 - ExerciseStatusBar

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6157812345c2700008b7db83?event_id=6157812300837484e7dd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
This is probably a valid error.

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**TypeError** in **/tracks/go/concepts**](https://app.bugsnag.com/exercism/v3-client-side/errors/6157812345c2700008b7db83?event_id=6157813e008371a8b2300000&i=gh&m=fx)
