### ISSUE TITLE
Hovering node on the concept tree should highlight ancestors path

### ISSUE THREAD

**Issue by iHiD** [exercism/website#202]
@neenjaw We've [discussed this before](https://exercism-team.slack.com/archives/DHGLRMJ1J/p1601402302003800), but I think it lost before we merged. Rather than just showing parents, the path should highlight ancestors and their lines.

**Comment by neenjaw** [comment]
Ah, I think i missed the `(all-)` part of the `(all-)ancestors`.  So basically you would like to trace the path from the concept up until the root?

**Comment by iHiD** [comment]
Correct! 👍

**Comment by neenjaw** [comment]
#205
