### ISSUE TITLE
SecurityError in /tracks/python/exercises

### ISSUE THREAD

**Issue by iHiD** [exercism/website#2021]
## Error in v3 (client side)

**SecurityError** in **/tracks/python/exercises**
Failed to execute 'pushState' on 'History': A history state object with URL 'https://exercism.org/tracks/python/exercises?status=available' cannot be created in a document with origin 'https://exercism-org.translate.goog' and URL 'https://exercism-org.translate.goog/tracks/python/exercises?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es-419&_x_tr_pto=nui,sc'.

[View on Bugsnag](https://app.bugsnag.com/exercism/v3-client-side/errors/6158f5a7bc0d2c000711924c?event_id=6158f5a700831fe7de650000&i=gh&m=ci)

## Stacktrace

    app/javascript/hooks/use-history.ts:28 - pushState
    app/javascript/hooks/use-history.ts:44 - 

[View full stacktrace](https://app.bugsnag.com/exercism/v3-client-side/errors/6158f5a7bc0d2c000711924c?event_id=6158f5a700831fe7de650000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SleeplessByte** [comment]
You can solve this by not pushing the url with host-and-domain, but attach that "just in time".
This happens because someone ran the site through Google Translate. 

Error is valid.

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**SecurityError** in **/tracks/python/exercises**](https://app.bugsnag.com/exercism/v3-client-side/errors/6158f5a7bc0d2c000711924c?event_id=6158f5a700831fe7de650000&i=gh&m=fx)
