### ISSUE TITLE
Webpacker fail to compile because of images

### ISSUE THREAD

**Issue by neenjaw** [exercism/website#212]
@ihid, when testing this locally, these [lines 80-81 of `application.tsx`](https://github.com/exercism/v3-website/blob/3571c5ffc2091a9d977b840188ec3970af223f2e/app/javascript/packs/application.tsx#L80-81) cause wepbacker to crash and not compile the javascript. 

It loads successfully when commented out

_Originally posted by @neenjaw in https://github.com/exercism/v3-website/pull/205#issuecomment-715683383_

## Expected Behavior

Webpacker to successfully complete

## Trouble Shooting performed

Rebased to master, re-pull dev-env images, restart docker dev-env

Finally commented out lines as described with success

**Comment by SleeplessByte** [comment]
(This might be a type error and if it is, happens when `webpack-env` isn't available in the types. You'll want to add `"types": ["webpack-env"]` to `tsconfig.json`, to make this require type resolve.)

**Comment by neenjaw** [comment]
I'll try that out

**Comment by neenjaw** [comment]
Still errors:
```text
Failed to compile.

./app/javascript/packs/application.tsx
Module not found: Error: Can't resolve '../images' in '/usr/src/app/app/javascript/packs'
```
Maybe I'm missing something that @iHiD has added locally to his

**Comment by iHiD** [comment]
Yeah, just comment if out for now. I have a local images folder which is empty but working which is why I don't get this locally. Sorry.

**Comment by iHiD** [comment]
This is now fixed on master and I've noted https://github.com/exercism/v3-website/issues/213
