### ISSUE TITLE
Discuss: Using Highlight.js for code highlighting on v3

### ISSUE THREAD

**Issue by joshgoebel** [exercism/website#219]
Jeremy asked me about this and I just wanted to brain dump and have some room for discussion or answer questions.  I'm the current maintainer of Highlight.js of course. Exercism v2 uses Prism of course.   This is a definitely more of a brain dump than a concise argument for or against.

So first a very, very high-level comparison and some quick thoughts off the top of my head of HLJS vs Prism:

- Prisms tries to be smaller (smaller runtime, smaller grammars), less complex, less context aware.  Your download size using HLJS would likely be larger - or you could serve individual files per grammar. (since it's easy to know which pages will contain which languages)
- Highlight.js tries to be higher fidelity, more complex (but not too complex), and slightly more aware of context.
- Prism currently highlights some things we don't (punctuation, operators), but I'm more than open to changing that for languages where it's possible to do so easily/correctly. (in the past we've avoided this type of higher fidelity highlighting of punctuation)
- Prism is open to new grammar contributions (I assume) where-as Highlight.js is closed (not enough core team to maintain them) - though it'd very easy to build and use 3rd party grammars with HLJS - and there is quite a list (in our [SUPPORTED_LANGUAGES.md](https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md) file).
- Highlight.js does not support IE11 or legacy browsers, I think Prism may still.
- Prism sometimes adds pure "style" conventions (such as `BLAH` [uppercase] being a constant) to grammars, where-as this isn't something HLJS encourages (though it hasn't been given much thought).  It's very helpful for a site like Exercism though. Of course it wouldn't be super hard to add back manually, but now you're possibly maintaining your own fork of certain grammars or patches that would need to be maintained over time - which is annoying.  
- I'd be open to a discussion about this but off the top of my head it seems an over-reach (I just told someone this regarding this question as it relates to Java and StackOverflow)... something we'd probably encourage by solving with a plug-in or patching the grammars (perhaps there is a way to make such patching less fragile though).

Jeremy also mentioned using a much newer editor and the desire for the editor to match the "viewer"... in which case I suggested it might just be better to figure out how to use the editors syntax highlighting EVERYWHERE.  Then you would have 100% consistency.  With either Prism or HLJS you're going to be fighting with differences between the grammars, themes, highlighting  philosophy (do we consider this a keyword or a built-in, etc). Some of those philosophical differences may possibly not be things we'd desire to "fix" (we might think they aren't broken).

I'd say overall HLJS might be a bit more "fiddly" than Prism.  Sometimes our desire to more nicely highlight things can get us into trouble such as [trying to highlight functions in C++](https://github.com/highlightjs/highlight.js/issues/1114):

```c++
CUrlQuery q(request.GetQuery() ? request.GetQuery() : "");
```

We think that's a function definition and highlight `q` as the name of a function (GitHub seems to also)... although it's actually a variable declaration.  This is because we're just a fancy pattern matcher, not a full parser.  So sometimes things like this just get tagged #cantfix because we'd still rather than the functions highlighted (so nice) even if every once in a while that means a mistake in highlighting a variable definition.  Sometimes Prism avoids this by just choosing not to highlight things.  For example for some languages Prism won't even try to highlight a regular expressions because it's hard to avoid things like math expressions with division incorrectly flagging as regex.  We try our best to get this right (and highlight the regex).

So often our "best effort" grammars get us really close (covering say 99% of common code) but then when someone finds an edge case it can be very apparent (broken highlighting, highlighting just stops half-way thru)... where-as Prism brushes such things off easier by simply doing less.  If you don't try to highlight it, you can't get it wrong.

---

Overall choosing Highlight.js is probably "more effort" than just sticking with Prism.  I have a feeling (at least initially) it'd result in more "bugs" with highlighting and programming effort than you would have with Prism - particular since you know Prism works very well from v2, and existing users are accustomed to it's behaviors/quirks.

Honestly finding some way to use the your fancy editors highlighting could be your best best - assuming it works well, is fast enough, has good syntax coverage, etc.  And doubly so if "themes editing/viewing must match precisely".  That said every large site with discerning users that adopts HLJS typically results in big improvements for HLJS, finding bugs, improving auto-detect, etc... so if Exercism.io choses HLJS it'd probably be of some benefit to us... StackExchange definitely has resulted in all sorts of recent activity (rebooting of a few poor grammars, etc), many bug fixes, etc... :-)

More than happy to answer any questions anyone has about what is or isn't possible and what can or can't be done with HLJS.

**Comment by iHiD** [comment]
Thanks, @joshgoebel!

Two quick comments

1. As a reference point, our Prism config is this:
- https://github.com/exercism/website/blob/master/config/initializers/prism.rb
- https://github.com/exercism/website/blob/master/lib/prism_js.rb
- https://github.com/exercism/website/blob/master/lib/prism_js/

2. With regards to:

> Jeremy also mentioned using a much newer editor and the desire for the editor to match the "viewer"... in which case I suggested it might just be better to figure out how to use the editors syntax highlighting EVERYWHERE. Then you would have 100% consistency

There's so many places we need highlighting (e.g. snippets in markdown files, or mentor comments) that I think loading an editor instance for each of those is going to be huge overkill, so I think we will need some highlighter still.

**Comment by joshgoebel** [comment]
> that I think loading an editor instance for each of those is going to be huge overkill

Well I'm not up to speed on what "loading an editor instance" entails. :-)  I suppose it could truly simply be too heavy... I wouldn't assume that by default (JS is VERY fast these days)... but if there was a delay/lag in using it for simpler cases then yes, perhaps something simpler would be optimal.

Regarding prism config:

- All the file mapping/aliasing is going to pretty much be the same... 
- You'd have to map your idea of language names to ours. (might be worth looking at what we're missing, etc - as you'd have to write and maintain those grammars yourself)
- We don't do line numbers out of the box.  It's not hard to add  (if you don't need line wrap). If you do need line wrap it's a bit harder (but still doable, just a little elbow grease).
- Highlighting individual lines of the output accurately may require a more involved line number implementation, or actually it might be as simple as adding a `span class='highlightline'` to the content before highlighting. You'd need to play with this.  I don't remember ever using this so I'm not sure exactly what the Prism plugin does here.
- The library doesn't include any automated auto-loading OOB either (although all our CDN modules can easily be loaded JIT)... so you'd need a small fetch/queue/highlight wrapper to make this work. Actually though you could do this purely statically also when the page is generated (rather than dynamically at runtime) - if you're still doing full page requests rather than some fancy SPA stuff.  Not sure how you're doing it now.  IE, just two `<script>` tags, done.

I'm not convinced you need auto-loading for EVERYTHING though... you can get a large number of bundled languages in just 50kb... now by the time you add every language on Exercism that might get more expensive, but I'd probably still suggest a core bundle and then auto-load the expensive grammars (in terms of byte size) separately...

**Comment by joshgoebel** [comment]
Looks like Prism is doing line numbers the "easy way". That's just a few lines of code... count lines, generate the list of line numbers, stick them in a div/span with flexbox, style, done... it gets harder if you want to properly handle line wrap... which involves the left hand knowing what the right hand is doing... so now you need to render the line number grouped with the line it relates to so that your wrapping  on the right doesn't break your line numbering on the left.

**Comment by iHiD** [comment]
We're now happily using highlightjs :)

**Comment by joshgoebel** [comment]
Any feedback or things you've noticed?  Did you tweak the grammars any or using this as is?

**Comment by SleeplessByte** [comment]
Using as is for now, but we'll PR to highlightjs repo if we find things we need 🗡️

**Comment by joshgoebel** [comment]
You probably lost `constant` (which is sad) but I'm in the process of adding that back to grammars where there is a strong enough convention (uppercase, etc)...

**Comment by SleeplessByte** [comment]
Yeah `SCREAMING_SNAKE_CASE` is a good convention in JavaScript and TypeScript and both `SCREAMING_SNAKE_CASE` and `PascalCase` for Ruby (where Anything that starts with a capital is language-wise a constant).

**Comment by joshgoebel** [comment]
Well in Ruby that would get flagged as a `title.class`.  Same in JS. (PascalCase)
