### ISSUE TITLE
org-wide-files trigger for new repos appears to be broken

### ISSUE THREAD

**Issue by SaschaMann** [exercism/website#2633]
I know this might be bad timing but it appears that the creation or publication of [exercism/job-application-process](https://github.com/exercism/job-application-process) did not trigger an [`org-wide-files` build](https://github.com/exercism/org-wide-files/actions).

This would also explain why we recently saw a failure on a merged commit due to trying to push to an empty repo, but no failure in a tracking issue for that repo alone which should have happened if a build was triggered either on publication or creation of said repo.

cc @ErikSchierboom 

(feel free to move to org-wide-files if that's a better fit but given that the other triggers work, I think this is an issue with the website-side of it)

**Comment by ErikSchierboom** [comment]
I've briefly looked into this, and found the issue: when we receive a `push` event (which we should get when a new repository is created), we have a guard that only dispatches the org-wide-files event if any of the org-wide-files related files were changed (so `.github/org-wide-files-config.toml` or any file in `.appends`). The new repos don't have these files, so the guard fails and no event is dispatched.

Having looked into the event payload, what we _can_ do is to check the event's `created` property, which is only set to true when `ref` is created (which is the branch). Combining that with checking that the `ref` is `refs/heads/main`, we should be able to detect a repository's first push. Thoughts?

**Comment by SaschaMann** [comment]
That sounds reasonable.

It's worth noting that the first branch that's pushed to a repo becomes the default branch, so the check for `refs/heads/main` might not be reliable. But that seems like an edge case where several things went wrong, so that we can probably safely ignore it.
