### ISSUE TITLE
CopyToClipboardButton broken

### ISSUE THREAD

**Issue by iHiD** [exercism/website#279]
When rendering this via the Bootloader, `navigator` is always `undefined` for me here so the component doesn't render.

https://github.com/exercism/v3-website/blob/7615ccf8b288909e4486e930155ac5c2e1915664/app/javascript/components/common/CopyToClipboardButton.tsx#L12

**Comment by ErikSchierboom** [comment]
Do you mean when rendering it like:

```
ReactComponents::Common::CopyToClipboardButton.new("exercism download --exercise=pattern")
```
?

When rendering it like that, it works for me in Chrome and Edge.

**Comment by SleeplessByte** [comment]
The clipboard API only works in secure contexts (https with valid certificate, localhost).

**Comment by ErikSchierboom** [comment]
I've just checked, and this does indeed now work on exercism.lol now that it's HTTPS.
