### ISSUE TITLE
Run tests in CI mode

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/website#28]
Run the js test in CI mode

**Comment by iHiD** [comment]
@ErikSchierboom I believe this works now. Pls confirm :)

**Comment by ErikSchierboom** [comment]
@iHiD I don't think it does. I think @SleeplessByte was referring to Jest's [`--ci` option](https://jestjs.io/docs/en/cli#--ci), which won't update any snapshots automatically but fail when they are invalid.

**Comment by SleeplessByte** [comment]
Mostly in non-interactive mode (which can be done using that flag, I think)

The difference is that the regular jest will show a menu at the end, or tell you that snapshots need to be update or whatevers, ci mode will exit with 0 or non zero depending on the results  .

Works out of the box when the CI environment flag is set, I think, which is a standard on many CIs.

You can test it by running jest and see if it exists, with or without --ci

**Comment by ErikSchierboom** [comment]
Having discussed this over Slack, it appears that there was a small misunderstanding regarding this issue. The tests don't need to run in CI mode as they are running while development is done on the website.
