### ISSUE TITLE
Filter Exercises by Difficulty

### ISSUE THREAD

**Issue by ghost** [exercism/website#2852]
Adding the ability to filter by "Learning Exercise", "Easy", "Medium", "Hard" would be very useful.

**Comment by iHiD** [comment]
@saurami Did you ignore this for a reason?

<img width="867" alt="Screenshot 2022-08-14 at 23 04 05" src="https://user-images.githubusercontent.com/286476/184556498-389d08e3-23eb-4fda-84c8-bd796b12dab9.png">

<img width="972" alt="Screenshot 2022-08-14 at 23 04 14" src="https://user-images.githubusercontent.com/286476/184556491-e160fb02-e5e3-4144-bddd-11af5c892b00.png">

**Comment by ghost** [comment]
Oh, I missed that.

**Comment by iHiD** [comment]
Thanks. I think this a duplicate of https://github.com/exercism/exercism/issues/6490
