### ISSUE TITLE
Empty files cause infinite loop

### ISSUE THREAD

**Issue by iHiD** [exercism/website#289]
@kntsoriano We have an issue where if the initial stub is empty, or you create an empty submission then refresh, stuff goes wrong.

See this video:
https://files.internetwolke.ovh/2020/11/ydncVtcAPD.mp4

I think there’s an issue with the local storage stuff. Maybe because `""` in JS is `false`, not `true` and some something is happening that you’re not expecting?

The Julia track has lots of empty stubs to experiment with (until @SaschaMann implements them :)). I've updated Julia/Lasagna as part of diagnosing this though.

**Comment by iHiD** [comment]
Update: In `app/javascript/components/student/editor/FileEditor.tsx` if you add the following before the final return:
```
    console.log("Pre-return")
    console.log(content)
    console.log(file.content)

    // Existing code
    return (
      <div>...
```

You'll see the infinite loop that it's in.

**Comment by iHiD** [comment]
If you're chilly, this is a great way to warm your lap up though! Or if you're too hot, it gets the fans going nicely ;)

**Comment by SaschaMann** [comment]
The video above will be deleted automatically in a few days, I reuploaded it: https://streamable.com/ul9e5x (GitHub doesn't like mp4s)
