### ISSUE TITLE
Implement state change in ToolingJob::Process 

### ISSUE THREAD

**Issue by iHiD** [exercism/website#35]
@ErikSchierboom: Something to get you into the Dynamodb codebase.

Once the processing is done in `ToolingJob::Process`, we want to update the status of the item to be processed.

This code from tooling invoker will probably be useful to you.

```ruby
      client.update_item(
        table_name: table_name,
        key: { id: job_id },
        expression_attribute_names: {
          "#JS": "job_status",
          "#LU": "locked_until"
        },
        expression_attribute_values: {
          ":js": "locked",
          ":lu": Time.now.to_i + 15
        },
        update_expression: "SET #JS = :js, #LU = :lu",
        return_values: "ALL_NEW"
      )
```

**Comment by ErikSchierboom** [comment]
@iHiD Is this issue still relevant? I see the above code in the [tooling-orchestrator](https://github.com/exercism/tooling-orchestrator/blob/master/lib/orchestrator/retrieve_next_job.rb#L40).

**Comment by iHiD** [comment]
Yes. Once the job is processed we need to update DynamoDB to set the `job_status` to `processed` (probably [here](https://github.com/exercism/v3-website/blob/master/app/commands/tooling_job/process.rb#L43)).

The code above was just a way of you seeing how to update the `job_status` 🙂
