### ISSUE TITLE
Fix broken images in site updates

### ISSUE THREAD

**Issue by iHiD** [exercism/website#3510]
Go to https://exercism.org/tracks/elixir/

Notice that the images are broken for exercise updates. This is because those images don't exist yet. We need a fallback image to work here. In other places we use `app/javascript/components/common/imageErrorHandler.tsx` for this

<img width="858" alt="Screenshot 2023-03-01 at 22 15 22" src="https://user-images.githubusercontent.com/286476/222277587-c2e75cad-fce1-4631-9a15-a49d0e973e2c.png">

**Comment by dem4ron** [comment]
Fixed in [#3513](https://github.com/exercism/website/pull/3513)
