### ISSUE TITLE
Add notifications React component

### ISSUE THREAD

**Issue by iHiD** [exercism/website#37]
- [x] Add a component which will be the notification icon in the website header. It has two states (representing whether you have new notifications or not, and a number of notifications). 
- [x] Trigger it at the end of the `Notification::Create` method.

**Comment by iHiD** [comment]
[This](https://github.com/exercism/v3-website/blob/master/app/commands/iteration/representation/process.rb#L53) is the equivelent trigger elsewhere for the notification.

**Comment by iHiD** [comment]
@ErikSchierboom @kntsoriano is going to work on this and send us a PR to review when he's got his head in the codebase. 

---

**General note:** I'm very keen to get a solid set of standards/helpers/tests/etc around these components, so let's ensure that we're all on the same page with this. I've showed Karlo the example one I did and the one Erik made as a basis to work from, but my thinking is still in flux on the best way to model much of this, and we all have different experience in React/Rails/etc so please both speak up if you think the things we're doing aren't the best way. All three of us care about writing good code, so we can be open and honest in our reviews of each other's work to get to the best possible place. I'm excited about nailing this with you both 🙂

**Comment by SleeplessByte** [comment]
(On testing this, I got some thoughts too, but let's wait for it to be there)
