### ISSUE TITLE
localstorage sharing files across exercises

### ISSUE THREAD

**Issue by iHiD** [exercism/website#382]
It seems that when I go to different exercises, the localstorage is giving me back the same files regardless of the language exercise. The storage should be scoped to `solution_id`

**Comment by SleeplessByte** [comment]
Storage should imo be scoped to track + slug, not solution id

**Comment by iHiD** [comment]
@SleeplessByte Reason?

**Comment by SleeplessByte** [comment]
Isn't solution id new per iteration? I don't see why we would want to store each iteration.

**Comment by iHiD** [comment]
A "solution" is a user+exercise. Solutions have many iterations. 

My main thinking for `solution_id` is if someone leaves a track and restart it then they would have a new `solution_id`.

**Comment by SleeplessByte** [comment]
In that case it's the same thing I wanted, so yes that's good :)
