### ISSUE TITLE
Add dyslexic font swap for users that want it

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/website#488]
https://www.opendyslexic.org/

**Comment by iHiD** [comment]
Thanks 💙  

I've read into it a bit more and decided not to add it. I'll defer to [this comment](https://github.com/antijingoist/open-dyslexic/issues/17#issuecomment-269055957) for my reasoning.

Specifically this quote was the key thing:
> Finally, the most harm may come when students who have already experienced significant struggle and academic failures related to learning to read, have yet another experience with failure when they are not able to read significantly better in a font designed to do so. A repeated failure experience can further damage students’ self-efficacy and academic self-esteem.

I also end with the same thought as in the comment:

> In the spirit of scientific inquiry, I welcome peer-reviewed scientific research that demonstrates such fonts can really help. Until then... :)

**Comment by SleeplessByte** [comment]
Absolutely agreed. I honestly expected there to be some already, but TIL.
