### ISSUE TITLE
Responding to review comments in one's own PRs rewards review rep

### ISSUE THREAD

**Issue by SaschaMann** [exercism/website#527]
The screenshot explains it better than words:

![grafik](https://user-images.githubusercontent.com/20866761/109163312-7b669280-7779-11eb-910e-3b821c926776.png)

Example PR: https://github.com/exercism/julia/pull/331

---

"Reviewing" my own PR by commenting on a comment by the reviewer also awards review rep. Presumably this would also happen when I add review comments to my PR as additional info for the reviewer.

**Comment by ErikSchierboom** [comment]
Aha, good catch!
