### ISSUE TITLE
Add mentoring table

### ISSUE THREAD

**Issue by kntsoriano** [exercism/website#57]
## Screenshot
<img width="1228" alt="Screenshot 2020-09-04 at 13 54 43" src="https://user-images.githubusercontent.com/1901520/92337472-94508e00-f0dc-11ea-8e24-870aefb6ef8a.png">

## Features
1. User sees all solutions that can be mentored. This should be paginated.
2. Allow user to filter solutions by student or exercise name.
3. Allow user to sort solutions, categories to be decided.
4. Allow user to filter by language. I'm assuming this is the button on the upper left corner.

## Questions
1. What do we call this component?
2. Near the mentee's name, what does the star and blue dot mean?
3. What do we call the field that contains "new iteration". Is that a status?

**Comment by kntsoriano** [comment]
@ErikSchierboom anything I missed?

**Comment by ErikSchierboom** [comment]
> User sees all solutions that can be mentored. This should be paginated.

I think that is the second table. This table is the list of open mentoring conversations (from the mentors viewpoint), right @taiyab?

> 1. What do we call this component?

The component is displayed on the mentor's workspace, so maybe it should start with `mentor`? Here are some options:

- mentor-list-conversations
- mentor-conversations-list
- mentored-students-list
- mentored-students

What do you think?

> 2. Near the mentee's name, what does the star and blue dot mean?

I think the star is when one has indicated that you liked that student in a previous conversation. I don't know about the blue dot. @taiyab could you chime in?

> 3. What do we call the field that contains "new iteration". Is that a status?

I believe this is shown when the student has submitted an iteration you, as the mentor, have not yet seen.

> @ErikSchierboom anything I missed?

There is a pop-up when one hovers over on of the students:

![image](https://user-images.githubusercontent.com/135246/92441566-be728080-f1ae-11ea-8fd8-18b43dcd4e94.png)

**Comment by taiyab** [comment]
>  This table is the list of open mentoring conversations (from the mentors viewpoint)

Yep. But it's not just open conversations, it's open conversations with something for the mentor TODO, i.e. the student has submitted a new iteration, or commented on an iteration. Once an item is addressed by the mentor, it'll disappear until the student does another action to bring it back.

This also means the area has a zero state, when all the items have been addressed in that list. (Think Inbox Zero).

@kntsoriano I'll be updating that pop-up content, but there will in essence be:
- Avatar
- Username
- Reputation
- Bio excerpt
- Your mentoring history with them (+ previously mentored status)
- Favourited student or not

The blue dot means you've successfully mentored them before. The visual may change as we're using it to mean "new" in other places.

If you're only focusing on this top area, then that's it for now.

**Comment by ErikSchierboom** [comment]
Thanks!

**Comment by kntsoriano** [comment]
Thanks. Everything is much clearer now :)

@ErikSchierboom With the info from @taiyab above, is it good to call this component`mentor-todos-list`? @taiyab would like to hear your thoughts on this as well.

I'll go with `mentor-conversations-list` for now just in order to get things going. The name should be easy to change in the future.

**Comment by SleeplessByte** [comment]
Given that it's modelled after email, maybe `mentor-inbox`?

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom With the info from @taiyab above, is it good to call this component `mentor-todos-list`? @taiyab would like to hear your thoughts on this as well.

Yes this is good!

> Given that it's modelled after email, maybe `mentor-inbox`?

Ooh, I also really like this! @taiyab @kntsoriano ?

**Comment by taiyab** [comment]
@ErikSchierboom @kntsoriano @SleeplessByte 

Naming isn't my forte, but both sound good to me.

If I were to try to come up with a criteria for naming, I'd say there will be other list, table-like components, which should share a prefix/suffix in naming.

**Comment by SleeplessByte** [comment]
I personally tend to abstract names publically and use structural names internally.

So I mean that that block / component is the inbox. Inside it there is a table, which might later become a list or a grid or whatever.

**Comment by taiyab** [comment]
@SleeplessByte Makes a lot of sense to me.

The whole component is a `mentor-inbox`, the subcomponents will be whatever they are.

If you look at the Testimonial page, it shares a very similar component (or subcomponents):
![image](https://user-images.githubusercontent.com/5337876/92604626-a1ba7380-f2a8-11ea-9fa6-2954b1942008.png)

**Comment by kntsoriano** [comment]
I like `mentor-inbox`!

**Comment by taiyab** [comment]
@kntsoriano I've updated the tooltip 
![image](https://user-images.githubusercontent.com/5337876/92753196-8ff8cf00-f381-11ea-9882-27896231f707.png)

It will later be updated to include a few other things (languages, country of origin, etc.)

**Comment by ErikSchierboom** [comment]
@SleeplessByte Do you have any suggestions for a library to use for the popup?

**Comment by SleeplessByte** [comment]
https://popper.js.org/

(for real, that's the only one I would recommend -- used by bootstrap too -- in this case; I _usually_ roll my own tho, because I don't need _all_ options but a very small subset. We will have more popups, so using this makes sense to me).

And since v2, is has `react` bindings: https://popper.js.org/react-popper/v2/#install

**Comment by ErikSchierboom** [comment]
Sweet, thanks!

**Comment by kntsoriano** [comment]
@iHiD I'm closing this now. I'll leave you to add an issue in the project management repo regarding the tooltip.
