### ISSUE TITLE
Add another mentoring table

### ISSUE THREAD

**Issue by kntsoriano** [exercism/website#66]
## Description
As discussed in our previous meeting, we also want to implement this other mentoring table. We're sticking to the table for now, not including the tabs on the top and the filters on the right side.

## Preview
![image](https://user-images.githubusercontent.com/1901520/93292201-953d9a00-f817-11ea-950c-e9a3ef8a7dd1.png)

## Questions
1. What do we call this component? Is `<MentorSolutionsList />` okay?
2. What are the "badge-like" things on the third column? cc @taiyab

**Comment by ErikSchierboom** [comment]
> 1. What do we call this component? Is <MentorSolutionsList /> okay?

I think so! 

> 2. What are the "badge-like" things on the third column?

I think they're sort of special statuses, but @taiyab will know better.

**Comment by iHiD** [comment]
> 2. What are the "badge-like" things on the third column?

@kntsoriano They're info tags. They'll be made up as we go really. Let's call them `tags` and have `tagClassName` and `tagText` or something? Then the Rails can decide what they are, and we can use CSS to render the icons. And don't have to integrate more deeply with JS on them.
