### ISSUE TITLE
The notifications/reputation dropdowns make VoiceOver unusable

### ISSUE THREAD

**Issue by iHiD** [exercism/website#671]
Whenever React does a lookup for new data it triggers VoiceOver causing the whole site to be unusable.

https://www.loom.com/share/53ae621ae99f42b8be7b4b22985ead5b

(cc @SleeplessByte pls!)

Also, @kntsoriano you should sample "**MERGE STATE. MERGE STATE.**" and use it in some music.

**Comment by SleeplessByte** [comment]
Eh. I don't know if it has anything to do with the "new data". I'd also need to see this in real HTML first :P.

**Comment by iHiD** [comment]
The data it's reading out is the JSON response from the reputation widget on the top bar (It's nothing to do with where the cursor is on the page). That reputation widget pings the server for new data (as a fallback for websockets I believe?) and that's what VoiceOver is intercepting.

**Comment by SleeplessByte** [comment]
Is the data (on the page, the displayed / rendered / html data) actually _changing_ ? Is the reputation widget marked with `role="status"` or `aria-live` ?

**Comment by iHiD** [comment]
I have no idea. I've not written any of it :) 

Is the data (on the page, the displayed / rendered / html data) actually changing - I don't think so, no. The data isn't, so it shouldn't be. But that would need checking.

The code is here https://github.com/exercism/website/blob/main/app/javascript/components/dropdowns/Reputation.tsx and in the nested dir, if you want to look before Karlo gets to it :)

**Comment by kntsoriano** [comment]
How can I replicate this? Should there be a new notification that comes in? I've tried going to the exercises page and it doesn't seem to have this problem.

**Comment by iHiD** [comment]
It's literally just what happens for me when logged in. The "MERGE STATUS" is presumably it reading out a reputation token, but I'm not doing anything to get those (I did this locally and I don't have any data being synced that could cause this locally)

I'll explore later to see if I can clarify the source.

**Comment by iHiD** [comment]
@kntsoriano OK, so it turns out that this was happening because GitHub was finishing CI in a different tab and then it started announcing the change very forcefully!! So this isn't our issue.

**Comment by SleeplessByte** [comment]
(you're welcome 😁)
