### ISSUE TITLE
Erik's cheating on the rep again

### ISSUE THREAD

**Issue by iHiD** [exercism/website#777]
<img width="1422" alt="Screenshot 2021-04-15 at 14 21 03" src="https://user-images.githubusercontent.com/286476/114876064-dc176080-9df5-11eb-9d84-b434b046fa06.png">

https://github.com/exercism/scala-test-runner/pull/7

The merge should only be 1.

**Comment by BethanyG** [comment]
_Its not just Erik....._  😉 

![image](https://user-images.githubusercontent.com/5923094/115495915-770ca200-a21d-11eb-85ae-d83c5ea0c173.png)
