### ISSUE TITLE
ActiveRecord::ValueTooLong in profiles#create

### ISSUE THREAD

**Issue by iHiD** [exercism/website#825]
## Error in v3

**ActiveRecord::ValueTooLong** in **profiles#create**
Mysql2::Error: Data too long for column 'pronouns' at row 1

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/6084a1c1d9158e000a3ff2f6?event_id=6084a1c10077af41aca10000&i=gh&m=ci)

## Stacktrace

    app/controllers/profiles_controller.rb:51 - create

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/6084a1c1d9158e000a3ff2f6?event_id=6084a1c10077af41aca10000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by SaschaMann** [comment]
(Same for location)

**Comment by iHiD** [comment]
@kntsoriano Can you set a max length of 100 chars on each in React pls? (Just stop them typing at that stage - you can probably use the `max` HTML attribute, rather than JS)
