### ISSUE TITLE
Refactor notification channel broadcast into method

### ISSUE THREAD

**Issue by iHiD** [exercism/website#84]
Pending #74 being merged:

I think the details of what goes into the websocket request is best encapsulated within the NotificationsChannel, so we should refactor [these lines](https://github.com/exercism/v3-website/pull/74/files#diff-a55d28c4509c8052a910d96e6cc421f9R11-R14) into `NotificationsChannel.broadcast_changed(user)`

**Comment by kntsoriano** [comment]
Closing this now.

**Comment by iHiD** [comment]
Thanks :)
