### ISSUE TITLE
TypeError in SyncTrackJob@default

### ISSUE THREAD

**Issue by iHiD** [exercism/website#874]
## Error in v3

**TypeError** in **SyncTrackJob@default**
no implicit conversion of Symbol into Integer

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/608a1249e1efd30007c97d5e?event_id=608a124900787c7b33120000&i=gh&m=ci)

## Stacktrace

    app/models/git/track.rb:59 - concept_exercises
    app/commands/git/sync_track.rb:74 - concept_exercises
    app/commands/git/sync_track.rb:39 - call
    app/jobs/sync_track_job.rb:5 - perform

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/608a1249e1efd30007c97d5e?event_id=608a124900787c7b33120000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by ErikSchierboom** [comment]
@iHiD I've looked into this and this is failing due to the research experiment repo's config.json being in the old format: https://github.com/exercism/research_experiment_1/blob/main/config.json Let me know if you want me to update that config and how.

**Comment by iHiD** [comment]
OK, thanks. I'll think about this next week.

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **SyncTracksJob@dribble**](https://app.bugsnag.com/exercism/v3/errors/608a1249e1efd30007c97d5e?event_id=6105d9b3007f86951f950000&i=gh&m=ra)

**Comment by iHiD** [comment]
@ErikSchierboom What do we want to do about this?

**Comment by ErikSchierboom** [comment]
@iHiD I'm thinking: just exclude the research-experiment repo from being synced? Or do we need it to be synced?

**Comment by iHiD** [comment]
Yep. Sounds good.

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Octokit::UnprocessableEntity** in **SyncTracksJob@dribble**](https://app.bugsnag.com/exercism/v3/errors/608a1249e1efd30007c97d5e?event_id=6125121b007f85def2740000&i=gh&m=ra)

**Comment by ErikSchierboom** [comment]
@iHiD Is this a retry of an old job?

**Comment by iHiD** [comment]
I don't think. It's auto-opened from Bugsnag. Maybe GitHub was down for a few mins?

**Comment by ErikSchierboom** [comment]
Ah, I now see what's wrong. It's the `javascript-legacy` repo that fails to sync. I'll send a PR.
