### ISSUE TITLE
Use git sha of track or exercise?

### ISSUE THREAD

**Issue by iHiD** [exercism/website#909]
Should these be the exercise.git_sha now we store that? Can you fix if so pls.

- https://github.com/exercism/website/blob/4b81bb1f8ce4ddcb9492b61863a377a54dda15c1/app/models/solution.rb#L45
- https://github.com/exercism/website/blob/4b81bb1f8ce4ddcb9492b61863a377a54dda15c1/app/models/solution.rb#L183

**Comment by ErikSchierboom** [comment]
I think so, as the exercise and solution are intimately linked.
