### ISSUE TITLE
StandardError in db:migrate

### ISSUE THREAD

**Issue by iHiD** [exercism/website#958]
## Error in v3

**StandardError** in **db:migrate**
An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'active_storage_variant_records' already exists

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/609db6902518530008adc113?event_id=609db690007bd65eadcd0000&i=gh&m=ci)

## Stacktrace

    db/migrate/20210513232857_create_active_storage_variant_records.active_storage.rb:4 - change

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/609db6902518530008adc113?event_id=609db690007bd65eadcd0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by iHiD** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**StandardError** in **db:migrate**](https://app.bugsnag.com/exercism/v3/errors/609db6902518530008adc113?event_id=609db690007bd65eadcd0000&i=gh&m=fx)

**Comment by iHiD** [comment]
An error linked to this issue has been reopened in Bugsnag
[**StandardError** in **db/migrate/20210513232857_create_active_storage_variant_records.active_storage.rb:4**](https://app.bugsnag.com/exercism/v3/errors/609db6902518530008adc113?event_id=60a7ab3e007c8cec2cb10000&i=gh&m=ra)

**Comment by ErikSchierboom** [comment]
I think we can close this, right @iHiD?
