### ISSUE TITLE
NoMethodError in webhooks/issue_updates#create

### ISSUE THREAD

**Issue by iHiD** [exercism/website#996]
## Error in v3

**NoMethodError** in **webhooks/issue_updates#create**
undefined method `[]' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/exercism/v3/errors/60a7aefb6d78500007612ac1?event_id=60a7aefb007c8b08c5b90000&i=gh&m=ci)

## Stacktrace

    app/controllers/webhooks/issue_updates_controller.rb:10 - create

[View full stacktrace](https://app.bugsnag.com/exercism/v3/errors/60a7aefb6d78500007612ac1?event_id=60a7aefb007c8b08c5b90000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by ErikSchierboom** [comment]
This should be fixed now.
